#!/bin/bash

INDEX="$1"
IP="$2"

if [ ! -z "$INDEX" ]; then
    if [ ! -z "$IP" ]; then
        ffmpeg -f v4l2 -i "/dev/video$INDEX" -preset ultrafast -vcodec libx264 -tune zerolatency -framerate 30 -f h264 "udp://$IP:5000"
    else
        ffmpeg -f v4l2 -i "/dev/video$INDEX" -preset ultrafast -vcodec libx264 -tune zerolatency -framerate 30 -f h264 udp://127.0.0.1:5000
    fi
fi
